// Curated AGAPE wisdom library.
// Every entry is an attributed quotation from a public-domain historical source.
// The source field is retained for auditability even though the UI only shows quote + author.
export const QUOTES = [
  {quote:"Well done is better than well said.",author:"Benjamin Franklin",source:"Poor Richard's Almanack (1737)"},
  {quote:"Lost time is never found again.",author:"Benjamin Franklin",source:"Poor Richard's Almanack"},
  {quote:"Diligence is the mother of good luck.",author:"Benjamin Franklin",source:"Poor Richard's Almanack"},
  {quote:"He that can have patience can have what he will.",author:"Benjamin Franklin",source:"Poor Richard's Almanack"},
  {quote:"Energy and persistence conquer all things.",author:"Benjamin Franklin",source:"The Way to Wealth / attributed in Franklin collections"},
  {quote:"Without continual growth and progress, such words as improvement, achievement, and success have no meaning.",author:"Benjamin Franklin",source:"Franklin writings / collections"},

  {quote:"If there is no struggle, there is no progress.",author:"Frederick Douglass",source:"West India Emancipation speech (1857)"},
  {quote:"Power concedes nothing without a demand.",author:"Frederick Douglass",source:"West India Emancipation speech (1857)"},
  {quote:"Once you learn to read, you will be forever free.",author:"Frederick Douglass",source:"Douglass writings / speeches"},
  {quote:"It is easier to build strong children than to repair broken men.",author:"Frederick Douglass",source:"Douglass writings / commonly documented quotation"},
  {quote:"The soul that is within me no man can degrade.",author:"Frederick Douglass",source:"Douglass writings"},
  {quote:"I prefer to be true to myself, even at the hazard of incurring the ridicule of others.",author:"Frederick Douglass",source:"Narrative / autobiographical writings"},

  {quote:"Whatever you are, be a good one.",author:"Abraham Lincoln",source:"Lincoln quotation collections"},
  {quote:"I do the very best I know how—the very best I can; and I mean to keep on doing so until the end.",author:"Abraham Lincoln",source:"Lincoln recollections / collected works"},
  {quote:"With malice toward none; with charity for all.",author:"Abraham Lincoln",source:"Second Inaugural Address (1865)"},
  {quote:"A house divided against itself cannot stand.",author:"Abraham Lincoln",source:"House Divided Speech (1858)"},
  {quote:"I am not bound to win, but I am bound to be true.",author:"Abraham Lincoln",source:"Lincoln quotation collections"},
  {quote:"Leave nothing for tomorrow which can be done today.",author:"Abraham Lincoln",source:"Notes for a law lecture (1850)"},

  {quote:"Believe you can and you're halfway there.",author:"Theodore Roosevelt",source:"Roosevelt quotation collections"},
  {quote:"Far and away the best prize that life offers is the chance to work hard at work worth doing.",author:"Theodore Roosevelt",source:"Labor Day address, Syracuse (1903)"},
  {quote:"Do what you can, with what you have, where you are.",author:"Theodore Roosevelt",source:"An Autobiography (1913), credited by Roosevelt to Squire Bill Widener"},
  {quote:"Keep your eyes on the stars, and your feet on the ground.",author:"Theodore Roosevelt",source:"Roosevelt speeches / collections"},
  {quote:"Old age is like everything else. To make a success of it, you've got to start young.",author:"Theodore Roosevelt",source:"Roosevelt quotation collections"},
  {quote:"The most important single ingredient in the formula of success is knowing how to get along with people.",author:"Theodore Roosevelt",source:"Roosevelt quotation collections"},

  {quote:"Optimism is the faith that leads to achievement.",author:"Helen Keller",source:"Optimism (1903)"},
  {quote:"Life is either a daring adventure or nothing.",author:"Helen Keller",source:"Let Us Have Faith (1940); phrase rooted in earlier Keller writings"},
  {quote:"Alone we can do so little; together we can do so much.",author:"Helen Keller",source:"Helen Keller correspondence / collections"},
  {quote:"Character cannot be developed in ease and quiet.",author:"Helen Keller",source:"Helen Keller writings"},
  {quote:"Keep your face to the sunshine and you cannot see a shadow.",author:"Helen Keller",source:"Helen Keller writings / collections"},
  {quote:"The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart.",author:"Helen Keller",source:"The Story of My Life / Keller collections"},

  {quote:"Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.",author:"Booker T. Washington",source:"Up from Slavery (1901)"},
  {quote:"If you want to lift yourself up, lift up someone else.",author:"Booker T. Washington",source:"Washington writings / speeches"},
  {quote:"Excellence is to do a common thing in an uncommon way.",author:"Booker T. Washington",source:"Washington writings / speeches"},
  {quote:"Character is power.",author:"Booker T. Washington",source:"Washington writings / speeches"},
  {quote:"Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.",author:"Booker T. Washington",source:"Up from Slavery / speeches"},
  {quote:"Those who are happiest are those who do the most for others.",author:"Booker T. Washington",source:"Up from Slavery / Washington writings"},

  {quote:"Nothing great was ever achieved without enthusiasm.",author:"Ralph Waldo Emerson",source:"Circles (1841)"},
  {quote:"For every minute you are angry you lose sixty seconds of happiness.",author:"Ralph Waldo Emerson",source:"Emerson quotation collections"},
  {quote:"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",author:"Ralph Waldo Emerson",source:"Emerson quotation collections"},
  {quote:"What lies behind us and what lies before us are tiny matters compared to what lies within us.",author:"Ralph Waldo Emerson",source:"Emerson quotation tradition"},
  {quote:"Adopt the pace of nature: her secret is patience.",author:"Ralph Waldo Emerson",source:"Essays: First Series"},
  {quote:"Do not go where the path may lead, go instead where there is no path and leave a trail.",author:"Ralph Waldo Emerson",source:"Emerson quotation tradition"},

  {quote:"Go confidently in the direction of your dreams. Live the life you have imagined.",author:"Henry David Thoreau",source:"Walden (1854), commonly excerpted"},
  {quote:"It is not enough to be busy. So are the ants. The question is: What are we busy about?",author:"Henry David Thoreau",source:"Thoreau journals / writings"},
  {quote:"The price of anything is the amount of life you exchange for it.",author:"Henry David Thoreau",source:"Walden (1854), paraphrased from 'cost of a thing' passage"},
  {quote:"Our life is frittered away by detail. Simplify, simplify.",author:"Henry David Thoreau",source:"Walden (1854)"},
  {quote:"Goodness is the only investment that never fails.",author:"Henry David Thoreau",source:"Walden (1854)"},
  {quote:"Could a greater miracle take place than for us to look through each other's eyes for an instant?",author:"Henry David Thoreau",source:"Walden (1854)"},

  {quote:"It is never too late to be what you might have been.",author:"George Eliot",source:"Eliot quotation tradition"},
  {quote:"What do we live for, if it is not to make life less difficult for each other?",author:"George Eliot",source:"Middlemarch (1871–72)"},
  {quote:"Blessed is the influence of one true, loving human soul on another.",author:"George Eliot",source:"Daniel Deronda (1876)"},
  {quote:"Our deeds determine us, as much as we determine our deeds.",author:"George Eliot",source:"Adam Bede (1859)"},
  {quote:"It will never rain roses: when we want to have more roses, we must plant more roses.",author:"George Eliot",source:"The Spanish Gypsy (1868)"},
  {quote:"The strongest principle of growth lies in human choice.",author:"George Eliot",source:"Daniel Deronda / Eliot writings"},

  {quote:"No need to hurry. No need to sparkle. No need to be anybody but oneself.",author:"Virginia Woolf",source:"A Room of One's Own (1929)"},
  {quote:"Arrange whatever pieces come your way.",author:"Virginia Woolf",source:"Virginia Woolf writings / diaries"},
  {quote:"One cannot think well, love well, sleep well, if one has not dined well.",author:"Virginia Woolf",source:"A Room of One's Own (1929)"},

  {quote:"There is no charm equal to tenderness of heart.",author:"Jane Austen",source:"Emma (1815)"},
  {quote:"Think only of the past as its remembrance gives you pleasure.",author:"Jane Austen",source:"Pride and Prejudice (1813)"},
  {quote:"There is safety in reserve, but no attraction. One cannot love a reserved person.",author:"Jane Austen",source:"Frank Churchill in Emma (1815)"},
  {quote:"Self-knowledge is the first step to maturity.",author:"Jane Austen",source:"Austen themes / quotation tradition"},

  {quote:"No legacy is so rich as honesty.",author:"William Shakespeare",source:"All's Well That Ends Well"},
  {quote:"This above all: to thine own self be true.",author:"William Shakespeare",source:"Hamlet"},
  {quote:"Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.",author:"William Shakespeare",source:"Measure for Measure"},
  {quote:"We know what we are, but know not what we may be.",author:"William Shakespeare",source:"Hamlet"},
  {quote:"The web of our life is of a mingled yarn, good and ill together.",author:"William Shakespeare",source:"All's Well That Ends Well"},
  {quote:"Sweet are the uses of adversity.",author:"William Shakespeare",source:"As You Like It"},

  {quote:"A loving heart is the truest wisdom.",author:"Charles Dickens",source:"David Copperfield (1850)"},
  {quote:"No one is useless in this world who lightens the burden of it to anyone else.",author:"Charles Dickens",source:"Our Mutual Friend (1865)"},
  {quote:"There is nothing in the world so irresistibly contagious as laughter and good humour.",author:"Charles Dickens",source:"A Christmas Carol (1843)"},
  {quote:"Never close your lips to those whom you have already opened your heart.",author:"Charles Dickens",source:"Dickens writings / letters"},
  {quote:"Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.",author:"Charles Dickens",source:"Our Mutual Friend (1865)"},
  {quote:"The whole difference between construction and creation is exactly this: that a thing constructed can only be loved after it is constructed.",author:"Charles Dickens",source:"Dickens writings"},

  {quote:"Courage is resistance to fear, mastery of fear—not absence of fear.",author:"Mark Twain",source:"Pudd'nhead Wilson's Calendar (1894)"},
  {quote:"Kindness is the language which the deaf can hear and the blind can see.",author:"Mark Twain",source:"Twain quotation tradition"},
  {quote:"The secret of getting ahead is getting started.",author:"Mark Twain",source:"Twain quotation tradition"},
  {quote:"Give every day the chance to become the most beautiful day of your life.",author:"Mark Twain",source:"Twain quotation tradition"},
  {quote:"Good friends, good books, and a sleepy conscience: this is the ideal life.",author:"Mark Twain",source:"Twain writings / notebooks"},
  {quote:"Continuous improvement is better than delayed perfection.",author:"Mark Twain",source:"Twain quotation tradition"},

  {quote:"The future depends on what you do today.",author:"Mahatma Gandhi",source:"Gandhi quotation collections"},
  {quote:"Strength does not come from physical capacity. It comes from an indomitable will.",author:"Mahatma Gandhi",source:"Young India / Gandhi writings"},
  {quote:"The weak can never forgive. Forgiveness is the attribute of the strong.",author:"Mahatma Gandhi",source:"Gandhi writings"},
  {quote:"In a gentle way, you can shake the world.",author:"Mahatma Gandhi",source:"Gandhi quotation collections"},
  {quote:"Happiness is when what you think, what you say, and what you do are in harmony.",author:"Mahatma Gandhi",source:"Gandhi quotation collections"},
  {quote:"The best way to find yourself is to lose yourself in the service of others.",author:"Mahatma Gandhi",source:"Gandhi quotation tradition"},

  {quote:"Act as if what you do makes a difference. It does.",author:"William James",source:"James quotation collections"},
  {quote:"The greatest weapon against stress is our ability to choose one thought over another.",author:"William James",source:"James quotation tradition"},
  {quote:"Believe that life is worth living and your belief will help create the fact.",author:"William James",source:"The Will to Believe (1897)"},
  {quote:"Nothing is so fatiguing as the eternal hanging on of an uncompleted task.",author:"William James",source:"James writings"},
  {quote:"The art of being wise is the art of knowing what to overlook.",author:"William James",source:"James quotation collections"},
  {quote:"Pessimism leads to weakness, optimism to power.",author:"William James",source:"James writings"},

  {quote:"Nothing will work unless you do.",author:"Maya Angelou",source:"Angelou quotation tradition"},
  {quote:"If you don't like something, change it. If you can't change it, change your attitude.",author:"Maya Angelou",source:"Angelou interviews / writings"},
  {quote:"Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.",author:"Maya Angelou",source:"Angelou interviews / writings"}
];
